// Extended movie data with cast information
export const moviesData = [
  {
    id: 1,
    title: 'The Shawshank Redemption',
    year: 1994,
    genre: 'Drama',
    rating: 9.3,
    duration: '142 min',
    description:
      'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    plot: 'Andy Dufresne, a successful banker, is arrested for the murders of his wife and her lover, and is sentenced to life imprisonment at the Shawshank State Penitentiary. He becomes the most unconventional prisoner.',
    cast: [
      { name: 'Tim Robbins', character: 'Andy Dufresne', id: 7 },
      { name: 'Morgan Freeman', character: "Ellis Boyd 'Red' Redding", id: 1 },
      { name: 'Bob Gunton', character: 'Warden Norton', id: 8 },
      { name: 'William Sadler', character: 'Heywood', id: 9 },
    ],
    director: 'Frank Darabont',
    writers: ['Stephen King', 'Frank Darabont'],
    budget: '$25 million',
    boxOffice: '$16.3 million',
    awards: ['7 Academy Award nominations'],
  },
  {
    id: 2,
    title: 'The Godfather',
    year: 1972,
    genre: 'Crime',
    rating: 9.2,
    duration: '175 min',
    description:
      'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    plot: 'The story spans the years 1945 to 1955 and chronicles the transformation of Michael Corleone from reluctant family outsider to ruthless mafia boss.',
    cast: [
      { name: 'Marlon Brando', character: 'Vito Corleone', id: 10 },
      { name: 'Al Pacino', character: 'Michael Corleone', id: 2 },
      { name: 'James Caan', character: 'Sonny Corleone', id: 11 },
      { name: 'Robert Duvall', character: 'Tom Hagen', id: 12 },
    ],
    director: 'Francis Ford Coppola',
    writers: ['Mario Puzo', 'Francis Ford Coppola'],
    budget: '$6 million',
    boxOffice: '$134.9 million',
    awards: ['3 Academy Awards', '5 Golden Globe nominations'],
  },
  {
    id: 3,
    title: 'The Dark Knight',
    year: 2008,
    genre: 'Action',
    rating: 9.0,
    duration: '152 min',
    description:
      'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.',
    plot: "Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and District Attorney Harvey Dent, but a psychopathic criminal mastermind known as the Joker threatens to undermine Batman's work.",
    cast: [
      { name: 'Christian Bale', character: 'Bruce Wayne / Batman', id: 3 },
      { name: 'Heath Ledger', character: 'The Joker', id: 13 },
      { name: 'Aaron Eckhart', character: 'Harvey Dent / Two-Face', id: 14 },
      { name: 'Michael Caine', character: 'Alfred Pennyworth', id: 15 },
    ],
    director: 'Christopher Nolan',
    writers: ['Jonathan Nolan', 'Christopher Nolan'],
    budget: '$185 million',
    boxOffice: '$1.005 billion',
    awards: ['2 Academy Awards', 'Heath Ledger posthumous Oscar'],
  },
  {
    id: 4,
    title: 'Pulp Fiction',
    year: 1994,
    genre: 'Crime',
    rating: 8.9,
    duration: '154 min',
    description:
      'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
    plot: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper.",
    cast: [
      { name: 'John Travolta', character: 'Vincent Vega', id: 16 },
      { name: 'Uma Thurman', character: 'Mia Wallace', id: 4 },
      { name: 'Samuel L. Jackson', character: 'Jules Winnfield', id: 17 },
      { name: 'Bruce Willis', character: 'Butch Coolidge', id: 18 },
    ],
    director: 'Quentin Tarantino',
    writers: ['Quentin Tarantino', 'Roger Avary'],
    budget: '$8 million',
    boxOffice: '$214.2 million',
    awards: ['1 Academy Award', "Palme d'Or at Cannes"],
  },
  {
    id: 5,
    title: 'Forrest Gump',
    year: 1994,
    genre: 'Drama',
    rating: 8.8,
    duration: '142 min',
    description:
      'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man.',
    plot: 'Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.',
    cast: [
      { name: 'Tom Hanks', character: 'Forrest Gump', id: 6 },
      { name: 'Robin Wright', character: 'Jenny Curran', id: 19 },
      { name: 'Gary Sinise', character: 'Lieutenant Dan Taylor', id: 20 },
      { name: 'Sally Field', character: 'Mrs. Gump', id: 21 },
    ],
    director: 'Robert Zemeckis',
    writers: ['Winston Groom', 'Eric Roth'],
    budget: '$55 million',
    boxOffice: '$677.9 million',
    awards: ['6 Academy Awards', '3 Golden Globe Awards'],
  },
  {
    id: 6,
    title: 'Inception',
    year: 2010,
    genre: 'Sci-Fi',
    rating: 8.8,
    duration: '148 min',
    description:
      'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    plot: 'Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state.',
    cast: [
      { name: 'Leonardo DiCaprio', character: 'Dom Cobb', id: 5 },
      { name: 'Marion Cotillard', character: 'Mal', id: 22 },
      { name: 'Tom Hardy', character: 'Eames', id: 23 },
      { name: 'Ellen Page', character: 'Ariadne', id: 24 },
    ],
    director: 'Christopher Nolan',
    writers: ['Christopher Nolan'],
    budget: '$160 million',
    boxOffice: '$836.8 million',
    awards: ['4 Academy Awards', '8 Academy Award nominations'],
  },
  {
    id: 7,
    title: 'The Matrix',
    year: 1999,
    genre: 'Sci-Fi',
    rating: 8.7,
    duration: '136 min',
    description:
      'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    plot: 'Neo, a computer programmer by day and hacker by night, is contacted by the mysterious Morpheus who reveals the shocking truth about reality.',
    cast: [
      { name: 'Keanu Reeves', character: 'Neo', id: 25 },
      { name: 'Laurence Fishburne', character: 'Morpheus', id: 26 },
      { name: 'Carrie-Anne Moss', character: 'Trinity', id: 27 },
      { name: 'Hugo Weaving', character: 'Agent Smith', id: 28 },
    ],
    director: 'The Wachowskis',
    writers: ['The Wachowskis'],
    budget: '$63 million',
    boxOffice: '$467.2 million',
    awards: ['4 Academy Awards'],
  },
  {
    id: 8,
    title: 'Goodfellas',
    year: 1990,
    genre: 'Crime',
    rating: 8.7,
    duration: '146 min',
    description:
      'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.',
    plot: 'Based on a true story, the film follows the rise and fall of mob associate Henry Hill and his friends over a period of time.',
    cast: [
      { name: 'Robert De Niro', character: 'Jimmy Conway', id: 29 },
      { name: 'Ray Liotta', character: 'Henry Hill', id: 30 },
      { name: 'Joe Pesci', character: 'Tommy DeVito', id: 31 },
      { name: 'Lorraine Bracco', character: 'Karen Hill', id: 32 },
    ],
    director: 'Martin Scorsese',
    writers: ['Nicholas Pileggi', 'Martin Scorsese'],
    budget: '$25 million',
    boxOffice: '$46.8 million',
    awards: ['1 Academy Award', '5 Academy Award nominations'],
  },
  {
    id: 9,
    title: 'The Lord of the Rings: The Return of the King',
    year: 2003,
    genre: 'Fantasy',
    rating: 8.9,
    duration: '201 min',
    description:
      "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom.",
    plot: 'The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth.',
    cast: [
      { name: 'Elijah Wood', character: 'Frodo Baggins', id: 33 },
      { name: 'Ian McKellen', character: 'Gandalf', id: 34 },
      { name: 'Viggo Mortensen', character: 'Aragorn', id: 35 },
      { name: 'Orlando Bloom', character: 'Legolas', id: 36 },
    ],
    director: 'Peter Jackson',
    writers: ['J.R.R. Tolkien', 'Peter Jackson'],
    budget: '$94 million',
    boxOffice: '$1.146 billion',
    awards: ['11 Academy Awards'],
  },
  {
    id: 10,
    title: 'Fight Club',
    year: 1999,
    genre: 'Drama',
    rating: 8.8,
    duration: '139 min',
    description:
      'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    plot: 'A depressed man suffering from insomnia meets a strange soap salesman named Tyler Durden and soon finds himself living in his squalid house.',
    cast: [
      { name: 'Brad Pitt', character: 'Tyler Durden', id: 37 },
      { name: 'Edward Norton', character: 'The Narrator', id: 38 },
      { name: 'Helena Bonham Carter', character: 'Marla Singer', id: 39 },
      { name: 'Meat Loaf', character: 'Robert Paulson', id: 40 },
    ],
    director: 'David Fincher',
    writers: ['Chuck Palahniuk', 'Jim Uhls'],
    budget: '$63 million',
    boxOffice: '$101.2 million',
    awards: ['Empire Award for Best Film'],
  },
  {
    id: 11,
    title: 'Star Wars: Episode IV - A New Hope',
    year: 1977,
    genre: 'Sci-Fi',
    rating: 8.6,
    duration: '121 min',
    description:
      'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy.',
    plot: 'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire.',
    cast: [
      { name: 'Mark Hamill', character: 'Luke Skywalker', id: 41 },
      { name: 'Harrison Ford', character: 'Han Solo', id: 42 },
      { name: 'Carrie Fisher', character: 'Princess Leia', id: 43 },
      { name: 'Alec Guinness', character: 'Obi-Wan Kenobi', id: 44 },
    ],
    director: 'George Lucas',
    writers: ['George Lucas'],
    budget: '$11 million',
    boxOffice: '$775.4 million',
    awards: ['7 Academy Awards'],
  },
  {
    id: 12,
    title: 'The Silence of the Lambs',
    year: 1991,
    genre: 'Thriller',
    rating: 8.6,
    duration: '118 min',
    description:
      'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.',
    plot: "Clarice Starling, a top student at the FBI's training academy, is asked to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath.",
    cast: [
      { name: 'Jodie Foster', character: 'Clarice Starling', id: 45 },
      { name: 'Anthony Hopkins', character: 'Dr. Hannibal Lecter', id: 46 },
      { name: 'Scott Glenn', character: 'Jack Crawford', id: 47 },
      { name: 'Ted Levine', character: 'Buffalo Bill', id: 48 },
    ],
    director: 'Jonathan Demme',
    writers: ['Thomas Harris', 'Ted Tally'],
    budget: '$19 million',
    boxOffice: '$272.7 million',
    awards: ['5 Academy Awards'],
  },
  {
    id: 13,
    title: 'Saving Private Ryan',
    year: 1998,
    genre: 'War',
    rating: 8.6,
    duration: '169 min',
    description:
      'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.',
    plot: 'Captain Miller leads his squad behind enemy lines to find Private Ryan, whose three brothers have been killed in combat.',
    cast: [
      { name: 'Tom Hanks', character: 'Captain Miller', id: 6 },
      { name: 'Matt Damon', character: 'Private Ryan', id: 49 },
      { name: 'Tom Sizemore', character: 'Sergeant Horvath', id: 50 },
      { name: 'Edward Burns', character: 'Private Reiben', id: 51 },
    ],
    director: 'Steven Spielberg',
    writers: ['Robert Rodat'],
    budget: '$70 million',
    boxOffice: '$482.3 million',
    awards: ['5 Academy Awards'],
  },
  {
    id: 14,
    title: 'Interstellar',
    year: 2014,
    genre: 'Sci-Fi',
    rating: 8.6,
    duration: '169 min',
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    plot: "Earth's future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind's survival: Interstellar travel.",
    cast: [
      { name: 'Matthew McConaughey', character: 'Cooper', id: 52 },
      { name: 'Anne Hathaway', character: 'Brand', id: 53 },
      { name: 'Jessica Chastain', character: 'Murph', id: 54 },
      { name: 'Michael Caine', character: 'Professor Brand', id: 15 },
    ],
    director: 'Christopher Nolan',
    writers: ['Christopher Nolan', 'Jonathan Nolan'],
    budget: '$165 million',
    boxOffice: '$701.8 million',
    awards: ['1 Academy Award', '5 Academy Award nominations'],
  },
  {
    id: 15,
    title: 'The Departed',
    year: 2006,
    genre: 'Crime',
    rating: 8.5,
    duration: '151 min',
    description:
      "An undercover cop and a police informant play a cat and mouse game with each other as they attempt to find out each other's identity.",
    plot: 'Two men from opposite sides of the law are undercover within the Massachusetts State Police and the Irish mafia, but violence and bloodshed boil.',
    cast: [
      { name: 'Leonardo DiCaprio', character: 'Billy Costigan', id: 5 },
      { name: 'Matt Damon', character: 'Colin Sullivan', id: 49 },
      { name: 'Jack Nicholson', character: 'Frank Costello', id: 55 },
      { name: 'Mark Wahlberg', character: 'Dignam', id: 56 },
    ],
    director: 'Martin Scorsese',
    writers: ['William Monahan'],
    budget: '$90 million',
    boxOffice: '$291.5 million',
    awards: ['4 Academy Awards'],
  },
  {
    id: 16,
    title: 'Gladiator',
    year: 2000,
    genre: 'Action',
    rating: 8.5,
    duration: '155 min',
    description:
      'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    plot: 'Maximus is a powerful Roman general, loved by the people and the aging Emperor, Marcus Aurelius. Before his death, the Emperor chooses Maximus to be his heir.',
    cast: [
      { name: 'Russell Crowe', character: 'Maximus', id: 57 },
      { name: 'Joaquin Phoenix', character: 'Commodus', id: 58 },
      { name: 'Connie Nielsen', character: 'Lucilla', id: 59 },
      { name: 'Oliver Reed', character: 'Proximo', id: 60 },
    ],
    director: 'Ridley Scott',
    writers: ['David Franzoni', 'John Logan'],
    budget: '$103 million',
    boxOffice: '$460.5 million',
    awards: ['5 Academy Awards'],
  },
  {
    id: 17,
    title: 'Titanic',
    year: 1997,
    genre: 'Romance',
    rating: 7.9,
    duration: '194 min',
    description:
      'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
    plot: '84 years later, a 100-year-old woman named Rose DeWitt Bukater tells the story to her granddaughter Lizzy Calvert about her life set in April 10th 1912.',
    cast: [
      { name: 'Leonardo DiCaprio', character: 'Jack Dawson', id: 5 },
      { name: 'Kate Winslet', character: 'Rose DeWitt Bukater', id: 61 },
      { name: 'Billy Zane', character: 'Cal Hockley', id: 62 },
      { name: 'Gloria Stuart', character: 'Old Rose', id: 63 },
    ],
    director: 'James Cameron',
    writers: ['James Cameron'],
    budget: '$200 million',
    boxOffice: '$2.257 billion',
    awards: ['11 Academy Awards'],
  },
  {
    id: 18,
    title: 'Avatar',
    year: 2009,
    genre: 'Sci-Fi',
    rating: 7.9,
    duration: '162 min',
    description:
      'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.',
    plot: 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
    cast: [
      { name: 'Sam Worthington', character: 'Jake Sully', id: 64 },
      { name: 'Zoe Saldana', character: 'Neytiri', id: 65 },
      { name: 'Sigourney Weaver', character: 'Dr. Grace Augustine', id: 66 },
      { name: 'Stephen Lang', character: 'Colonel Quaritch', id: 67 },
    ],
    director: 'James Cameron',
    writers: ['James Cameron'],
    budget: '$237 million',
    boxOffice: '$2.923 billion',
    awards: ['3 Academy Awards'],
  },
  {
    id: 19,
    title: 'The Avengers',
    year: 2012,
    genre: 'Action',
    rating: 8.0,
    duration: '143 min',
    description:
      "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
    plot: 'Nick Fury is compelled to launch the Avengers Initiative when Loki poses a threat to planet Earth. His squad of superheroes put their minds together to accomplish the task.',
    cast: [
      { name: 'Robert Downey Jr.', character: 'Tony Stark / Iron Man', id: 68 },
      {
        name: 'Chris Evans',
        character: 'Steve Rogers / Captain America',
        id: 69,
      },
      { name: 'Mark Ruffalo', character: 'Bruce Banner / Hulk', id: 70 },
      { name: 'Chris Hemsworth', character: 'Thor', id: 71 },
    ],
    director: 'Joss Whedon',
    writers: ['Joss Whedon', 'Zak Penn'],
    budget: '$220 million',
    boxOffice: '$1.519 billion',
    awards: ['Academy Award nomination'],
  },
  {
    id: 20,
    title: 'Jurassic Park',
    year: 1993,
    genre: 'Adventure',
    rating: 8.2,
    duration: '127 min',
    description:
      "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
    plot: 'Huge advancements in scientific technology have enabled a mogul to create an island full of living dinosaurs. John Hammond has invited four individuals to witness the spectacle.',
    cast: [
      { name: 'Sam Neill', character: 'Dr. Alan Grant', id: 72 },
      { name: 'Laura Dern', character: 'Dr. Ellie Sattler', id: 73 },
      { name: 'Jeff Goldblum', character: 'Dr. Ian Malcolm', id: 74 },
      { name: 'Richard Attenborough', character: 'John Hammond', id: 75 },
    ],
    director: 'Steven Spielberg',
    writers: ['Michael Crichton', 'David Koepp'],
    budget: '$63 million',
    boxOffice: '$1.029 billion',
    awards: ['3 Academy Awards'],
  },
  {
    id: 21,
    title: 'The Lion King',
    year: 1994,
    genre: 'Animation',
    rating: 8.5,
    duration: '88 min',
    description:
      'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
    plot: 'A young lion prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savannah.',
    cast: [
      { name: 'Matthew Broderick', character: 'Adult Simba (voice)', id: 76 },
      { name: 'Jeremy Irons', character: 'Scar (voice)', id: 77 },
      { name: 'James Earl Jones', character: 'Mufasa (voice)', id: 78 },
      { name: 'Moira Kelly', character: 'Adult Nala (voice)', id: 79 },
    ],
    director: 'Roger Allers',
    writers: ['Irene Mecchi', 'Jonathan Roberts'],
    budget: '$45 million',
    boxOffice: '$968.5 million',
    awards: ['2 Academy Awards'],
  },
  {
    id: 22,
    title: 'Casablanca',
    year: 1942,
    genre: 'Romance',
    rating: 8.5,
    duration: '102 min',
    description:
      'A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.',
    plot: 'In Casablanca, Morocco in December 1941, a cynical American expatriate meets a former lover, with unforeseen complications.',
    cast: [
      { name: 'Humphrey Bogart', character: 'Rick Blaine', id: 80 },
      { name: 'Ingrid Bergman', character: 'Ilsa Lund', id: 81 },
      { name: 'Paul Henreid', character: 'Victor Laszlo', id: 82 },
      { name: 'Claude Rains', character: 'Captain Renault', id: 83 },
    ],
    director: 'Michael Curtiz',
    writers: ['Julius J. Epstein', 'Philip G. Epstein'],
    budget: '$1 million',
    boxOffice: '$4.2 million',
    awards: ['3 Academy Awards'],
  },
  {
    id: 23,
    title: 'Parasite',
    year: 2019,
    genre: 'Thriller',
    rating: 8.5,
    duration: '132 min',
    description:
      'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    plot: 'The Kim family lives in a basement and struggles to make ends meet. When they get the opportunity to work for the wealthy Park family, their lives take a dramatic turn.',
    cast: [
      { name: 'Song Kang-ho', character: 'Ki-taek', id: 84 },
      { name: 'Lee Sun-kyun', character: 'Park Dong-ik', id: 85 },
      { name: 'Cho Yeo-jeong', character: 'Choi Yeon-gyo', id: 86 },
      { name: 'Choi Woo-shik', character: 'Ki-woo', id: 87 },
    ],
    director: 'Bong Joon-ho',
    writers: ['Bong Joon-ho', 'Han Jin-won'],
    budget: '$11.4 million',
    boxOffice: '$258.8 million',
    awards: ['4 Academy Awards'],
  },
  {
    id: 24,
    title: 'Whiplash',
    year: 2014,
    genre: 'Drama',
    rating: 8.5,
    duration: '106 min',
    description:
      "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    plot: 'Andrew Neiman is an ambitious young jazz drummer, in pursuit of rising to the top of his elite music conservatory. Terence Fletcher, an instructor known for his terrifying teaching methods, discovers Andrew.',
    cast: [
      { name: 'Miles Teller', character: 'Andrew Neiman', id: 88 },
      { name: 'J.K. Simmons', character: 'Terence Fletcher', id: 89 },
      { name: 'Paul Reiser', character: 'Jim Neiman', id: 90 },
      { name: 'Melissa Benoist', character: 'Nicole', id: 91 },
    ],
    director: 'Damien Chazelle',
    writers: ['Damien Chazelle'],
    budget: '$3.3 million',
    boxOffice: '$49 million',
    awards: ['3 Academy Awards'],
  },
];

export const actorsData = [
  {
    id: 1,
    name: 'Morgan Freeman',
    age: 86,
    nationality: 'American',
    birthDate: 'June 1, 1937',
    birthPlace: 'Memphis, Tennessee, USA',
    knownFor: ['The Shawshank Redemption', 'Se7en', 'Million Dollar Baby'],
    bio: 'Morgan Freeman is an American actor, director, and narrator known for his distinctive deep voice and various roles in a wide variety of film genres.',
    fullBio:
      'Morgan Freeman is one of the most recognizable figures in American cinema. His career spans over five decades, during which he has appeared in numerous acclaimed films. He is known for his deep, authoritative voice and his ability to bring gravitas to any role. Freeman has been nominated for an Academy Award five times, winning once for Best Supporting Actor for his role in Million Dollar Baby.',
    filmography: [
      {
        title: 'The Shawshank Redemption',
        year: 1994,
        character: "Ellis Boyd 'Red' Redding",
      },
      { title: 'Se7en', year: 1995, character: 'Detective William Somerset' },
      {
        title: 'Million Dollar Baby',
        year: 2004,
        character: "Eddie 'Scrap-Iron' Dupris",
      },
      { title: 'The Dark Knight', year: 2008, character: 'Lucius Fox' },
    ],
    awards: [
      'Academy Award for Best Supporting Actor',
      'Golden Globe Award',
      'Screen Actors Guild Award',
    ],
  },
  {
    id: 2,
    name: 'Al Pacino',
    age: 83,
    nationality: 'American',
    birthDate: 'April 25, 1940',
    birthPlace: 'East Harlem, New York, USA',
    knownFor: ['The Godfather', 'Scarface', 'Scent of a Woman'],
    bio: 'Alfredo James Pacino is an American actor and filmmaker. He is the recipient of numerous accolades including an Academy Award, two Tony Awards, and two Primetime Emmy Awards.',
    fullBio:
      'Al Pacino is considered one of the greatest actors in the history of cinema. He is known for his intense method acting style and his ability to portray complex, often troubled characters. Pacino achieved the Triple Crown of Acting, having won an Academy Award, two Tony Awards, and two Primetime Emmy Awards. He is particularly famous for his roles in crime dramas.',
    filmography: [
      { title: 'The Godfather', year: 1972, character: 'Michael Corleone' },
      { title: 'Scarface', year: 1983, character: 'Tony Montana' },
      { title: 'Scent of a Woman', year: 1992, character: 'Frank Slade' },
      { title: 'Heat', year: 1995, character: 'Vincent Hanna' },
    ],
    awards: [
      'Academy Award for Best Actor',
      '2 Tony Awards',
      '2 Emmy Awards',
      'Cecil B. DeMille Award',
    ],
  },
  {
    id: 3,
    name: 'Christian Bale',
    age: 50,
    nationality: 'British',
    birthDate: 'January 30, 1974',
    birthPlace: 'Haverfordwest, Wales',
    knownFor: ['The Dark Knight', 'American Psycho', 'The Machinist'],
    bio: 'Christian Charles Philip Bale is an English actor. Known for his versatility and physical transformations for his roles, he has been a leading man in films of several genres.',
    fullBio:
      'Christian Bale is renowned for his commitment to his craft, often undergoing dramatic physical transformations for his roles. He has portrayed a wide range of characters, from the emaciated insomniac in The Machinist to the muscular Batman in The Dark Knight trilogy. His dedication to method acting and his ability to completely embody his characters has made him one of the most respected actors of his generation.',
    filmography: [
      { title: 'American Psycho', year: 2000, character: 'Patrick Bateman' },
      { title: 'The Machinist', year: 2004, character: 'Trevor Reznik' },
      {
        title: 'The Dark Knight',
        year: 2008,
        character: 'Bruce Wayne / Batman',
      },
      { title: 'The Fighter', year: 2010, character: 'Dicky Eklund' },
    ],
    awards: [
      'Academy Award for Best Supporting Actor',
      'BAFTA Award',
      'Golden Globe Award',
    ],
  },
  {
    id: 4,
    name: 'Uma Thurman',
    age: 54,
    nationality: 'American',
    birthDate: 'April 29, 1970',
    birthPlace: 'Boston, Massachusetts, USA',
    knownFor: ['Pulp Fiction', 'Kill Bill', 'Batman & Robin'],
    bio: 'Uma Karuna Thurman is an American actress and former model. She has performed in a variety of films, from romantic comedies and dramas to science fiction and action films.',
    fullBio:
      "Uma Thurman rose to prominence in the 1990s with her collaborations with director Quentin Tarantino. Her iconic performance as Mia Wallace in Pulp Fiction earned her an Academy Award nomination and established her as one of Hollywood's leading actresses. She later starred as The Bride in Tarantino's Kill Bill films, showcasing her action star capabilities.",
    filmography: [
      { title: 'Pulp Fiction', year: 1994, character: 'Mia Wallace' },
      { title: 'Kill Bill: Vol. 1', year: 2003, character: 'The Bride' },
      { title: 'Kill Bill: Vol. 2', year: 2004, character: 'The Bride' },
      { title: 'Gattaca', year: 1997, character: 'Irene Cassini' },
    ],
    awards: [
      'Academy Award nomination',
      'Golden Globe Award',
      'BAFTA Award nomination',
    ],
  },
  {
    id: 5,
    name: 'Leonardo DiCaprio',
    age: 49,
    nationality: 'American',
    birthDate: 'November 11, 1974',
    birthPlace: 'Los Angeles, California, USA',
    knownFor: ['Inception', 'Titanic', 'The Wolf of Wall Street'],
    bio: 'Leonardo Wilhelm DiCaprio is an American actor and film producer. Known for his work in biographical and period films, he has received numerous accolades.',
    fullBio:
      'Leonardo DiCaprio is one of the most acclaimed actors of his generation, known for his intense performances and his collaboration with renowned directors. He has been nominated for seven Academy Awards and won one for The Revenant. Beyond acting, DiCaprio is also known for his environmental activism and his production company Appian Way Productions.',
    filmography: [
      { title: 'Titanic', year: 1997, character: 'Jack Dawson' },
      { title: 'Inception', year: 2010, character: 'Dom Cobb' },
      {
        title: 'The Wolf of Wall Street',
        year: 2013,
        character: 'Jordan Belfort',
      },
      { title: 'The Revenant', year: 2015, character: 'Hugh Glass' },
    ],
    awards: [
      'Academy Award for Best Actor',
      '3 Golden Globe Awards',
      'BAFTA Award',
    ],
  },
  {
    id: 6,
    name: 'Tom Hanks',
    age: 67,
    nationality: 'American',
    birthDate: 'July 9, 1956',
    birthPlace: 'Concord, California, USA',
    knownFor: ['Forrest Gump', 'Cast Away', 'Philadelphia'],
    bio: 'Thomas Jeffrey Hanks is an American actor and filmmaker. Known for both his comedic and dramatic roles, he is one of the most popular and recognizable film stars worldwide.',
    fullBio:
      'Tom Hanks is widely regarded as one of the greatest actors of all time, known for his everyman persona and his ability to bring warmth and humanity to his characters. He has won two consecutive Academy Awards for Best Actor and has been nominated for numerous other awards. Hanks is also a successful filmmaker and has produced several acclaimed films.',
    filmography: [
      { title: 'Philadelphia', year: 1993, character: 'Andrew Beckett' },
      { title: 'Forrest Gump', year: 1994, character: 'Forrest Gump' },
      { title: 'Cast Away', year: 2000, character: 'Chuck Noland' },
      {
        title: 'Saving Private Ryan',
        year: 1998,
        character: 'Captain John Miller',
      },
    ],
    awards: [
      '2 Academy Awards for Best Actor',
      '4 Golden Globe Awards',
      'Presidential Medal of Freedom',
    ],
  },
  {
    id: 25,
    name: 'Keanu Reeves',
    age: 59,
    nationality: 'Canadian',
    birthDate: 'September 2, 1964',
    birthPlace: 'Beirut, Lebanon',
    knownFor: ['The Matrix', 'John Wick', 'Speed'],
    bio: 'Keanu Charles Reeves is a Canadian actor. Born in Beirut and raised in Toronto, Reeves began acting in theatre productions and in television films before making his feature film debut.',
    fullBio:
      'Keanu Reeves has become one of the most beloved actors in Hollywood, known for his versatility and humble personality. From action films like The Matrix and John Wick to romantic dramas, Reeves has shown remarkable range throughout his career spanning over three decades.',
    filmography: [
      { title: 'The Matrix', year: 1999, character: 'Neo' },
      { title: 'John Wick', year: 2014, character: 'John Wick' },
      { title: 'Speed', year: 1994, character: 'Jack Traven' },
      { title: 'Point Break', year: 1991, character: 'Johnny Utah' },
    ],
    awards: ['Hollywood Walk of Fame Star', 'MTV Movie Award'],
  },
  {
    id: 29,
    name: 'Robert De Niro',
    age: 80,
    nationality: 'American',
    birthDate: 'August 17, 1943',
    birthPlace: 'New York City, New York, USA',
    knownFor: ['Taxi Driver', 'Goodfellas', 'The Godfather Part II'],
    bio: 'Robert Anthony De Niro Jr. is an American actor, producer, and director. He is particularly known for his collaborations with filmmaker Martin Scorsese.',
    fullBio:
      "Robert De Niro is widely regarded as one of the greatest actors of all time. Known for his intense method acting approach, De Niro has portrayed a wide range of characters throughout his career. His collaborations with Martin Scorsese have produced some of cinema's most memorable films.",
    filmography: [
      { title: 'Taxi Driver', year: 1976, character: 'Travis Bickle' },
      { title: 'Goodfellas', year: 1990, character: 'Jimmy Conway' },
      {
        title: 'The Godfather Part II',
        year: 1974,
        character: 'Vito Corleone',
      },
      { title: 'Raging Bull', year: 1980, character: 'Jake LaMotta' },
    ],
    awards: [
      '2 Academy Awards',
      'Golden Globe Award',
      'BAFTA Award',
      'Screen Actors Guild Award',
    ],
  },
  {
    id: 37,
    name: 'Brad Pitt',
    age: 60,
    nationality: 'American',
    birthDate: 'December 18, 1963',
    birthPlace: 'Shawnee, Oklahoma, USA',
    knownFor: ['Fight Club', "Ocean's Eleven", 'Once Upon a Time in Hollywood'],
    bio: 'William Bradley Pitt is an American actor and film producer. He has received multiple awards, including two Golden Globe Awards and an Academy Award for his acting.',
    fullBio:
      'Brad Pitt is one of the most recognizable and influential actors in Hollywood. Beyond his acting career, he has also established himself as a successful producer through his production company Plan B Entertainment, which has produced numerous critically acclaimed films.',
    filmography: [
      { title: 'Fight Club', year: 1999, character: 'Tyler Durden' },
      { title: "Ocean's Eleven", year: 2001, character: 'Rusty Ryan' },
      {
        title: 'Once Upon a Time in Hollywood',
        year: 2019,
        character: 'Cliff Booth',
      },
      { title: 'Se7en', year: 1995, character: 'Detective David Mills' },
    ],
    awards: [
      'Academy Award for Best Supporting Actor',
      '2 Golden Globe Awards',
      'BAFTA Award',
    ],
  },
  {
    id: 42,
    name: 'Harrison Ford',
    age: 81,
    nationality: 'American',
    birthDate: 'July 13, 1942',
    birthPlace: 'Chicago, Illinois, USA',
    knownFor: ['Star Wars', 'Indiana Jones', 'Blade Runner'],
    bio: 'Harrison Ford is an American actor. As of 2019, the U.S. domestic box-office grosses of his films total over $5.4 billion with worldwide grosses surpassing $9.3 billion.',
    fullBio:
      "Harrison Ford is one of Hollywood's most enduring and successful actors, known for his iconic roles as Han Solo in Star Wars and Indiana Jones. His career spans over five decades, during which he has become one of the highest-grossing actors of all time.",
    filmography: [
      { title: 'Star Wars', year: 1977, character: 'Han Solo' },
      {
        title: 'Raiders of the Lost Ark',
        year: 1981,
        character: 'Indiana Jones',
      },
      { title: 'Blade Runner', year: 1982, character: 'Rick Deckard' },
      { title: 'The Fugitive', year: 1993, character: 'Dr. Richard Kimble' },
    ],
    awards: [
      'AFI Life Achievement Award',
      'Cecil B. DeMille Award',
      "Honorary Palme d'Or",
    ],
  },
  {
    id: 45,
    name: 'Jodie Foster',
    age: 61,
    nationality: 'American',
    birthDate: 'November 19, 1962',
    birthPlace: 'Los Angeles, California, USA',
    knownFor: ['The Silence of the Lambs', 'Taxi Driver', 'Contact'],
    bio: 'Alicia Christian Foster is an American actress, director, and producer. She has received two Academy Awards, three British Academy Film Awards, two Golden Globe Awards, and the Cecil B. DeMille Award.',
    fullBio:
      'Jodie Foster began her career as a child actor and has since become one of the most respected actresses in Hollywood. Known for her intelligence and versatility, Foster has successfully transitioned from child star to serious dramatic actress and accomplished director.',
    filmography: [
      {
        title: 'The Silence of the Lambs',
        year: 1991,
        character: 'Clarice Starling',
      },
      { title: 'Taxi Driver', year: 1976, character: 'Iris Steensma' },
      { title: 'Contact', year: 1997, character: 'Dr. Eleanor Arroway' },
      { title: 'The Accused', year: 1988, character: 'Sarah Tobias' },
    ],
    awards: [
      '2 Academy Awards for Best Actress',
      '3 BAFTA Awards',
      '2 Golden Globe Awards',
      'Cecil B. DeMille Award',
    ],
  },
  {
    id: 46,
    name: 'Anthony Hopkins',
    age: 86,
    nationality: 'Welsh',
    birthDate: 'December 31, 1937',
    birthPlace: 'Margam, Wales',
    knownFor: ['The Silence of the Lambs', 'The Father', 'Thor'],
    bio: 'Sir Philip Anthony Hopkins is a Welsh actor, director, and producer. Considered to be one of the greatest living actors, Hopkins is well known for his portrayal of Hannibal Lecter.',
    fullBio:
      'Anthony Hopkins is widely regarded as one of the finest actors of his generation. His portrayal of Hannibal Lecter in The Silence of the Lambs is considered one of the greatest performances in cinema history. Hopkins was knighted by Queen Elizabeth II in 1993 for his services to the arts.',
    filmography: [
      {
        title: 'The Silence of the Lambs',
        year: 1991,
        character: 'Dr. Hannibal Lecter',
      },
      { title: 'The Father', year: 2020, character: 'Anthony' },
      { title: 'Thor', year: 2011, character: 'Odin' },
      {
        title: 'The Remains of the Day',
        year: 1993,
        character: 'James Stevens',
      },
    ],
    awards: [
      '2 Academy Awards for Best Actor',
      '2 Emmy Awards',
      'BAFTA Award',
      'Knighthood',
    ],
  },
  {
    id: 49,
    name: 'Matt Damon',
    age: 53,
    nationality: 'American',
    birthDate: 'October 8, 1970',
    birthPlace: 'Cambridge, Massachusetts, USA',
    knownFor: ['Good Will Hunting', 'The Bourne Identity', 'The Martian'],
    bio: "Matthew Paige Damon is an American actor, producer, and screenwriter. Ranked among Forbes' most bankable stars, the films in which he has appeared have collectively earned over $3.88 billion at the North American box office.",
    fullBio:
      "Matt Damon rose to prominence with Good Will Hunting, which he co-wrote and starred in, earning him an Academy Award for Best Original Screenplay. He has since become one of Hollywood's most versatile and bankable stars, known for his roles in both action films and dramas.",
    filmography: [
      { title: 'Good Will Hunting', year: 1997, character: 'Will Hunting' },
      { title: 'The Bourne Identity', year: 2002, character: 'Jason Bourne' },
      { title: 'The Martian', year: 2015, character: 'Mark Watney' },
      { title: 'Saving Private Ryan', year: 1998, character: 'Private Ryan' },
    ],
    awards: [
      'Academy Award for Best Original Screenplay',
      'Golden Globe Award',
      'BAFTA Award',
    ],
  },
  {
    id: 52,
    name: 'Matthew McConaughey',
    age: 54,
    nationality: 'American',
    birthDate: 'November 4, 1969',
    birthPlace: 'Uvalde, Texas, USA',
    knownFor: ['Dallas Buyers Club', 'Interstellar', 'True Detective'],
    bio: 'Matthew David McConaughey is an American actor and producer. He first gained notice for his supporting performance in the coming-of-age comedy Dazed and Confused.',
    fullBio:
      'Matthew McConaughey experienced a career renaissance in the 2010s, transitioning from romantic comedies to serious dramatic roles. His performance in Dallas Buyers Club earned him an Academy Award, and his work in True Detective was critically acclaimed.',
    filmography: [
      { title: 'Dallas Buyers Club', year: 2013, character: 'Ron Woodroof' },
      { title: 'Interstellar', year: 2014, character: 'Cooper' },
      { title: 'True Detective', year: 2014, character: 'Rust Cohle' },
      { title: 'The Wolf of Wall Street', year: 2013, character: 'Mark Hanna' },
    ],
    awards: [
      'Academy Award for Best Actor',
      'Golden Globe Award',
      "Critics' Choice Award",
    ],
  },
  {
    id: 53,
    name: 'Anne Hathaway',
    age: 41,
    nationality: 'American',
    birthDate: 'November 12, 1982',
    birthPlace: 'New York City, New York, USA',
    knownFor: ['Les Misérables', 'The Devil Wears Prada', 'Interstellar'],
    bio: 'Anne Jacqueline Hathaway is an American actress. The recipient of various accolades, including an Academy Award, a Golden Globe Award, and a Primetime Emmy Award.',
    fullBio:
      'Anne Hathaway began her career in family-friendly films before transitioning to more mature roles. Her versatility as an actress has been demonstrated through her work in musicals, dramas, and comedies. She won an Academy Award for her supporting role in Les Misérables.',
    filmography: [
      { title: 'Les Misérables', year: 2012, character: 'Fantine' },
      { title: 'The Devil Wears Prada', year: 2006, character: 'Andy Sachs' },
      { title: 'Interstellar', year: 2014, character: 'Brand' },
      {
        title: 'The Princess Diaries',
        year: 2001,
        character: 'Mia Thermopolis',
      },
    ],
    awards: [
      'Academy Award for Best Supporting Actress',
      'Golden Globe Award',
      'BAFTA Award',
      'Emmy Award',
    ],
  },
  {
    id: 57,
    name: 'Russell Crowe',
    age: 59,
    nationality: 'New Zealand',
    birthDate: 'April 7, 1964',
    birthPlace: 'Wellington, New Zealand',
    knownFor: ['Gladiator', 'A Beautiful Mind', 'The Insider'],
    bio: 'Russell Ira Crowe is an actor, director, musician, and singer. Although a New Zealand citizen, he has lived most of his life in Australia and identifies as an Australian.',
    fullBio:
      'Russell Crowe is known for his intense and committed performances in a wide range of films. His portrayal of Maximus in Gladiator earned him an Academy Award for Best Actor. Crowe is also known for his collaborations with director Ridley Scott.',
    filmography: [
      { title: 'Gladiator', year: 2000, character: 'Maximus Decimus Meridius' },
      { title: 'A Beautiful Mind', year: 2001, character: 'John Nash' },
      { title: 'The Insider', year: 1999, character: 'Jeffrey Wigand' },
      {
        title: 'Master and Commander',
        year: 2003,
        character: 'Captain Jack Aubrey',
      },
    ],
    awards: [
      'Academy Award for Best Actor',
      'BAFTA Award',
      'Golden Globe Award',
      'Screen Actors Guild Award',
    ],
  },
  {
    id: 61,
    name: 'Kate Winslet',
    age: 48,
    nationality: 'British',
    birthDate: 'October 5, 1975',
    birthPlace: 'Reading, England',
    knownFor: [
      'Titanic',
      'The Reader',
      'Eternal Sunshine of the Spotless Mind',
    ],
    bio: 'Kate Elizabeth Winslet is an English actress. Known for her work in independent films, particularly period dramas, and for her portrayals of headstrong and complicated women.',
    fullBio:
      'Kate Winslet gained international recognition for her role as Rose in Titanic. She has since established herself as one of the most talented actresses of her generation, known for choosing challenging and diverse roles. She won an Academy Award for her performance in The Reader.',
    filmography: [
      { title: 'Titanic', year: 1997, character: 'Rose DeWitt Bukater' },
      { title: 'The Reader', year: 2008, character: 'Hanna Schmitz' },
      {
        title: 'Eternal Sunshine of the Spotless Mind',
        year: 2004,
        character: 'Clementine Kruczynski',
      },
      { title: 'Revolutionary Road', year: 2008, character: 'April Wheeler' },
    ],
    awards: [
      'Academy Award for Best Actress',
      'Emmy Award',
      'Grammy Award',
      '3 Golden Globe Awards',
    ],
  },
  {
    id: 68,
    name: 'Robert Downey Jr.',
    age: 58,
    nationality: 'American',
    birthDate: 'April 4, 1965',
    birthPlace: 'New York City, New York, USA',
    knownFor: ['Iron Man', 'Sherlock Holmes', 'Tropic Thunder'],
    bio: 'Robert John Downey Jr. is an American actor and producer. His career has been characterized by critical and popular success in his youth, followed by a period of substance abuse and legal troubles.',
    fullBio:
      'Robert Downey Jr. experienced a remarkable career comeback, becoming one of the highest-paid actors in Hollywood through his portrayal of Tony Stark/Iron Man in the Marvel Cinematic Universe. His charismatic performances and quick wit have made him a fan favorite.',
    filmography: [
      { title: 'Iron Man', year: 2008, character: 'Tony Stark / Iron Man' },
      { title: 'Sherlock Holmes', year: 2009, character: 'Sherlock Holmes' },
      { title: 'Tropic Thunder', year: 2008, character: 'Kirk Lazarus' },
      {
        title: 'Avengers: Endgame',
        year: 2019,
        character: 'Tony Stark / Iron Man',
      },
    ],
    awards: ['Golden Globe Award', 'BAFTA Award', 'Screen Actors Guild Award'],
  },
  {
    id: 69,
    name: 'Chris Evans',
    age: 42,
    nationality: 'American',
    birthDate: 'June 13, 1981',
    birthPlace: 'Boston, Massachusetts, USA',
    knownFor: ['Captain America', 'Knives Out', 'Snowpiercer'],
    bio: 'Christopher Robert Evans is an American actor, best known for his role as Captain America in the Marvel Cinematic Universe series of films.',
    fullBio:
      'Chris Evans gained worldwide recognition for his portrayal of Steve Rogers/Captain America in the Marvel Cinematic Universe. Before his superhero fame, Evans appeared in various films and has since diversified his roles, showing his range as an actor in films like Knives Out.',
    filmography: [
      {
        title: 'Captain America: The First Avenger',
        year: 2011,
        character: 'Steve Rogers / Captain America',
      },
      { title: 'Knives Out', year: 2019, character: 'Hugh Ransom Drysdale' },
      { title: 'Snowpiercer', year: 2013, character: 'Curtis Everett' },
      {
        title: 'The Avengers',
        year: 2012,
        character: 'Steve Rogers / Captain America',
      },
    ],
    awards: ['Teen Choice Award', "People's Choice Award", 'Saturn Award'],
  },
  {
    id: 72,
    name: 'Sam Neill',
    age: 76,
    nationality: 'New Zealand',
    birthDate: 'September 14, 1947',
    birthPlace: 'Omagh, Northern Ireland',
    knownFor: ['Jurassic Park', 'The Piano', 'Hunt for Red October'],
    bio: 'Nigel John Dermot Neill is a New Zealand actor, director, producer, and screenwriter. Neill is best known for his starring role as paleontologist Dr. Alan Grant in Jurassic Park.',
    fullBio:
      "Sam Neill is one of New Zealand's most internationally recognized actors. His portrayal of Dr. Alan Grant in Jurassic Park brought him worldwide fame, but he has had a diverse career spanning drama, thriller, and comedy films across several decades.",
    filmography: [
      { title: 'Jurassic Park', year: 1993, character: 'Dr. Alan Grant' },
      { title: 'The Piano', year: 1993, character: 'Alisdair Stewart' },
      {
        title: 'Hunt for Red October',
        year: 1990,
        character: 'Captain Vasily Borodin',
      },
      { title: 'Dead Calm', year: 1989, character: 'John Ingram' },
    ],
    awards: ['New Zealand Order of Merit', 'Logie Award', 'AACTA Award'],
  },
  {
    id: 74,
    name: 'Jeff Goldblum',
    age: 71,
    nationality: 'American',
    birthDate: 'October 22, 1952',
    birthPlace: 'West Homestead, Pennsylvania, USA',
    knownFor: ['Jurassic Park', 'Independence Day', 'The Fly'],
    bio: 'Jeffrey Lynn Goldblum is an American actor and musician. He has starred in some of the highest-grossing films of his era, such as Jurassic Park and Independence Day.',
    fullBio:
      'Jeff Goldblum is known for his distinctive speaking style and eccentric personality both on and off screen. His memorable performances in science fiction films have made him a cult figure, and his unique approach to acting has influenced many contemporary performers.',
    filmography: [
      { title: 'Jurassic Park', year: 1993, character: 'Dr. Ian Malcolm' },
      { title: 'Independence Day', year: 1996, character: 'David Levinson' },
      { title: 'The Fly', year: 1986, character: 'Seth Brundle' },
      { title: 'Thor: Ragnarok', year: 2017, character: 'Grandmaster' },
    ],
    awards: [
      'Saturn Award',
      'Lifetime Achievement Award from the National Board of Review',
    ],
  },
  {
    id: 80,
    name: 'Humphrey Bogart',
    age: 57,
    nationality: 'American',
    birthDate: 'December 25, 1899',
    birthPlace: 'New York City, New York, USA',
    knownFor: ['Casablanca', 'The Maltese Falcon', 'The African Queen'],
    bio: 'Humphrey DeForest Bogart was an American film and stage actor. His performances in Classical Hollywood cinema films made him an American cultural icon.',
    fullBio:
      'Humphrey Bogart is widely regarded as one of the greatest actors in the history of American cinema. His tough-guy persona and distinctive voice made him a legend of the film noir genre. His performance in Casablanca is considered one of the greatest in cinema history.',
    filmography: [
      { title: 'Casablanca', year: 1942, character: 'Rick Blaine' },
      { title: 'The Maltese Falcon', year: 1941, character: 'Sam Spade' },
      { title: 'The African Queen', year: 1951, character: 'Charlie Allnut' },
      { title: 'The Big Sleep', year: 1946, character: 'Philip Marlowe' },
    ],
    awards: [
      'Academy Award for Best Actor',
      'AFI Life Achievement Award',
      'Hollywood Walk of Fame Star',
    ],
  },
  {
    id: 81,
    name: 'Ingrid Bergman',
    age: 67,
    nationality: 'Swedish',
    birthDate: 'August 29, 1915',
    birthPlace: 'Stockholm, Sweden',
    knownFor: ['Casablanca', 'Notorious', 'Gaslight'],
    bio: 'Ingrid Bergman was a Swedish actress who starred in a variety of European and American films, television movies, and plays.',
    fullBio:
      'Ingrid Bergman was one of the most internationally successful actresses from the Golden Age of Hollywood. Known for her natural beauty and acting ability, she won three Academy Awards and is remembered for her roles in classic films like Casablanca and Notorious.',
    filmography: [
      { title: 'Casablanca', year: 1942, character: 'Ilsa Lund' },
      { title: 'Notorious', year: 1946, character: 'Alicia Huberman' },
      { title: 'Gaslight', year: 1944, character: 'Paula Alquist Anton' },
      { title: 'Spellbound', year: 1945, character: 'Dr. Constance Petersen' },
    ],
    awards: [
      '3 Academy Awards',
      '2 Emmy Awards',
      'Tony Award',
      '4 Golden Globe Awards',
    ],
  },
  {
    id: 84,
    name: 'Song Kang-ho',
    age: 56,
    nationality: 'South Korean',
    birthDate: 'January 17, 1967',
    birthPlace: 'Gimhae, South Korea',
    knownFor: ['Parasite', 'The Host', 'Memories of Murder'],
    bio: 'Song Kang-ho is a South Korean actor. Regarded as one of the best actors of the 21st century, he is most known for his collaborations with directors Bong Joon-ho and Park Chan-wook.',
    fullBio:
      "Song Kang-ho is considered one of South Korea's finest actors and has been a key figure in the Korean Wave. His collaborations with acclaimed directors have resulted in some of the most critically acclaimed Korean films of the past two decades.",
    filmography: [
      { title: 'Parasite', year: 2019, character: 'Ki-taek' },
      { title: 'The Host', year: 2006, character: 'Park Gang-du' },
      { title: 'Memories of Murder', year: 2003, character: 'Park Doo-man' },
      { title: 'Snowpiercer', year: 2013, character: 'Namgoong Minsoo' },
    ],
    awards: [
      'Screen Actors Guild Award',
      'Cannes Film Festival Award',
      'Blue Dragon Film Award',
    ],
  },
  {
    id: 88,
    name: 'Miles Teller',
    age: 37,
    nationality: 'American',
    birthDate: 'February 20, 1987',
    birthPlace: 'Downingtown, Pennsylvania, USA',
    knownFor: ['Whiplash', 'Top Gun: Maverick', 'The Spectacular Now'],
    bio: 'Miles Alexander Teller is an American actor. Born in Pennsylvania and raised in Florida, he made his feature film debut in Rabbit Hole.',
    fullBio:
      'Miles Teller gained critical acclaim for his intense performance in Whiplash, which showcased his dedication to his craft. He has since appeared in a variety of films, from indie dramas to big-budget blockbusters like Top Gun: Maverick.',
    filmography: [
      { title: 'Whiplash', year: 2014, character: 'Andrew Neiman' },
      {
        title: 'Top Gun: Maverick',
        year: 2022,
        character: "Lt. Bradley 'Rooster' Bradshaw",
      },
      { title: 'The Spectacular Now', year: 2013, character: 'Sutter Keely' },
      {
        title: 'Fantastic Four',
        year: 2015,
        character: 'Reed Richards / Mr. Fantastic',
      },
    ],
    awards: [
      'Sundance Film Festival Award',
      "Critics' Choice Award nomination",
    ],
  },
  {
    id: 89,
    name: 'J.K. Simmons',
    age: 69,
    nationality: 'American',
    birthDate: 'January 9, 1955',
    birthPlace: 'Grosse Pointe, Michigan, USA',
    knownFor: ['Whiplash', 'Spider-Man', 'Juno'],
    bio: 'Jonathan Kimble Simmons is an American actor, considered one of the most prolific character actors of his generation.',
    fullBio:
      'J.K. Simmons is known for his versatility and intensity as a character actor. His terrifying portrayal of the abusive music instructor in Whiplash earned him an Academy Award and is considered one of the most memorable performances in recent cinema.',
    filmography: [
      { title: 'Whiplash', year: 2014, character: 'Terence Fletcher' },
      { title: 'Spider-Man', year: 2002, character: 'J. Jonah Jameson' },
      { title: 'Juno', year: 2007, character: 'Mac MacGuff' },
      { title: 'La La Land', year: 2016, character: 'Bill' },
    ],
    awards: [
      'Academy Award for Best Supporting Actor',
      'BAFTA Award',
      'Golden Globe Award',
      "Critics' Choice Award",
    ],
  },
];

// Helper functions
export function getMovieById(id: number) {
  return moviesData.find((movie) => movie.id === id);
}

export function getActorById(id: number) {
  return actorsData.find((actor) => actor.id === id);
}

// Updated search function to work with new cast structure
export function searchMoviesAndActors(query: string) {
  const searchTerm = query.toLowerCase().trim();

  if (!searchTerm) return { movies: [], actors: [] };

  // Search movies by title
  const moviesByTitle = moviesData.filter((movie) =>
    movie.title.toLowerCase().includes(searchTerm),
  );

  // Search movies by cast (now using cast array with name property)
  const moviesByCast = moviesData.filter((movie) =>
    movie.cast.some((actor) => actor.name.toLowerCase().includes(searchTerm)),
  );

  // Combine and remove duplicates
  const allMovies = [...moviesByTitle, ...moviesByCast];
  const uniqueMovies = allMovies.filter(
    (movie, index, self) => index === self.findIndex((m) => m.id === movie.id),
  );

  // Search actors by name
  const actors = actorsData.filter((actor) =>
    actor.name.toLowerCase().includes(searchTerm),
  );

  return {
    movies: uniqueMovies,
    actors: actors,
  };
}
